name: Bump package version

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Bump version'
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier:check
      - run: npm run test
      - run: npx tsc --noEmit
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          NEW_VERSION=$(npm version ${{ github.event.inputs.bump }})
          echo "New version: $NEW_VERSION"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main "$NEW_VERSION"
          gh api repos/${{ github.repository }}/dispatches \
            -f event_type=npm-publish \
            -F client_payload[tag]="$NEW_VERSION"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ github.token }}

      - name: Generate TypeDoc
        run: npx typedoc --entryPoints src/index.ts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
